apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: etcd
  namespace: demo
  labels:
    helm.sh/chart: karpor-0.6.0
    app.kubernetes.io/name: karpor
    app.kubernetes.io/component: etcd
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: 0.4.7
spec:
  serviceName: etcd
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: karpor
      app.kubernetes.io/component: etcd
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        app.kubernetes.io/name: karpor
        app.kubernetes.io/component: etcd
        app.kubernetes.io/instance: release-name
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.5.11
          imagePullPolicy: IfNotPresent 
          command:
            - /usr/local/bin/etcd
            - --listen-client-urls=http://0.0.0.0:2379
            - --advertise-client-urls=http://localhost:2379
          env:
            - name: ETCD_DATA_DIR
              value: /etcd-data/default.etcd
          ports:
            - containerPort: 2379 
          volumeMounts:
            - name: data
              mountPath: /etcd-data
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 10Gi
              memory: 1Gi
            requests:
              cpu: 250m
              ephemeral-storage: 2Gi
              memory: 256Mi
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: "11Gi"